language: node_js

node_js:
- '10'
- '9'
- '8'
- '7'
- '6'

matrix:
  fast_finish: true

script:
- npm run lint
- npm run compile

sudo: false

deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: GYFdcDOOzralC0XLy373evJurvEFoowW1ml6lTFVtTU06wCaVgGgm/uJhB3IuXqlAQG0p06qsOxuxMGzCHwO6FjV7th0qRl1vYLmmslR9CZ0oKrcsS1R72FtcNV/t3VqNOMW0ZebESTxoPVlzpXGkXFKVsl4JP6jwvQ0XtSfwtOh0UEbJ9IKCHRPsFUaYizdoNPrmdJ7v4ICa0dCyh0aFIna6l/I3P1UjYWT0HvQR5r56t9ErdywBMtPXDcHxR0dpXk1QoF9T85lboCAkyKxUY3+jv2IejPwc8aEf1WJm01rR9UaHzrZGJeRkau8p+RNw2gArY7EOL9IUPcVi6CYexxRXS8+nOgEx8Aaym9EE0husjHmI88K4HgEpRzfFXAiamjbuZWbZSPNt3VC7YeVgmKmSBShB94LRPmTHGuA35s9a/MqBEoe8mrTGKhn87ReLiZyAEkbH1jzJJ7HsfHXlwfVAPG7bH0UE/vnoXZfRFNT7djColryur62BGftPWP1x81k9xQJo/uw5IQ1FXNNFLC+4paHped/iDvu2nbUpwJiogbe4JYlHI3axpuo9EFMBbGWUYT1Vy7kMB9E16mqa2ZwQ7reiRjAArpgfTh4udPdfKqIc4SoDnwEQ93tTBkAGFkOB1RVgFJ2WS8wcbaBqsPqpPrpUCPHJWLh209c4Rk=
  skip_cleanup: true
  on:
    tags: true
    repo: browserspy/common
