language: node_js

node_js:
- '10'
- '9'
- '8'
- '7'
- '6'

matrix:
  fast_finish: true

script:
- npm run lint
- npm run compile

sudo: false

before_deploy:
- cd ./dist/src

deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: epVYPVQnro23I167sQOEYOBnwY50/1+cL7DxcZPkXmehKlZuSK3WVN8EUOJ0/SNAUQtWh1RqNhvnw+m3UQ6wlj7PMZRig1M34k6qaNmPX7vFawogdh4lq1+2CVPUbhCXmrk4kMCYidVMlQgQVDJczDzrJ4GrO2L8jDBcTev4N5rX9qB4mBREj9itJtDuVu06Ch7BCm5CV41uAm4qMK0FdvzKHlMAm4wAHqPhH8RoIOX7TeEIifwKoVmuuv99RJznJntanoOtiRb0lHaYxhpBThzwu59Ke8tx34ZVMhfXL/27QlgKze1KT9Nxlu+N02TFRic5Q3r96WesjkyIYyW3Lr8rIywEVBJOQsXOBTj3D3iHuzLamFVjV5wh4FO44G0pzxWFy9UU+20Acsj7nQX66YQEDik+oBxwyBJJe75ODohg3GaucOXZzLoA9l4kRz0qOCsPhXOowl0gFJxpkl07iFtWbG0QulohgH+HDAEAUZsobEilCU/djORWXxtfUOCm/3zYBAZvWYIvhHdgi1Roqx5dcVKzXQpd5cpMndyLw0Ms9yVlAZOe7kZo1wE2I6IKOcmxNX+6JK1YIpFCGsAN0HNGu+UubSN7KICR+7SWLwhTGpaa7WPFSYZrj92F0OEkY0tTTYt/VY/s8bcQm8z0AqsSzVyApyKP5BmJ2BOGGs4=
  skip_cleanup: true
  on:
    tags: true
    repo: browserspy/common
